### ISSUE TITLE
Send HTML content

### ISSUE THREAD

**Issue by rico237** [jingwanhsu/parse-server-mail-template-adapter#1]
Is it possible to send an HTML formated content.

Using .html instead of .txt

Thank you

**Comment by jingwanhsu** [comment]
@rico237 It depends on what low-layer adaptor (for example, `parse-server-sendgrid-adapter` in the sample) you use to access the mail server. What this adaptor do is only parse the template and send it to low-layer adaptor. It can surely parse the html file, but if you want to send an HTML formatted content, you have to make sure the low-layer adaptor do ask the mail server to send it with type HTML. So there's nothing I can do on this adaptor since it doesn't access the mail server.
